name: Run Bot Vang Daily

on:
  schedule:
    - cron: '0 16 * * *'  # Chạy đúng 00 phút, 16 giờ UTC (tức 23:00 VN)
  workflow_dispatch:      # Nút bấm thủ công vẫn giữ nguyên

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Cập nhật lên v4 cho ổn định bác nhé

      - name: Set up Python
        uses: actions/setup-python@v4 # Cập nhật lên v4 luôn
        with:
          python-python: '3.9'

      - name: Install dependencies
        run: |
          pip install python-telegram-bot sxtwl matplotlib

      - name: Run bot
        run: python main.py
