name: Run Bot Vang Daily

on:
  schedule:
    - cron: '00 16 * * *'  # Chạy đúng 23:00 giờ VN (16:00 UTC)
  workflow_dispatch:      # Nút bấm chạy tay để test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Sửa từ gạch dưới thành gạch ngang

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot sxtwl matplotlib

      - name: Run bot
        run: python phongthuy.py
